import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignIn,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "G7Cars Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
<ClerkProvider >
      <html lang="en">
        <body>
          <SignedIn>
          {children}
          </SignedIn>
      
        </body>
      </html>
    </ClerkProvider>
  );
}
